version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
      - run:
          name: Install tox
          command: |
            pip install tox
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            tox
